server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    # eureka 访问界面设置账号密码
    user:
      name: root
      password: 123456

eureka:
  instance:
    hostname: eureka-server
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      #eureka server接口,http://ip:port/eureka/为内部固定服务地址
#      #集群配置,使用逗号分隔，只需配置同步服务。
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@192.168.1.25:${server.port}/eureka/
#      defaultZone: http://192.168.180.15:9992/eureka/,http://192.168.180.15:9993/eureka/

